-- MySQL Script generated by MySQL Workbench
-- Fri Aug 11 15:32:41 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hsrrs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hsrrs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hsrrs` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `hsrrs` ;

-- -----------------------------------------------------
-- Table `hsrrs`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hsrrs`.`room` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `room_no` INT NOT NULL,
  `room_details` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hsrrs`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hsrrs`.`position` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pos_des` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hsrrs`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hsrrs`.`department` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dept_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hsrrs`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hsrrs`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `emp_name` VARCHAR(100) NOT NULL,
  `pos_id` INT NOT NULL,
  `dept_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_EMPLOYEE_JOB1_idx` (`pos_id` ASC),
  INDEX `dept_idx` (`dept_id` ASC),
  CONSTRAINT `fk_EMPLOYEE_JOB1`
    FOREIGN KEY (`pos_id`)
    REFERENCES `hsrrs`.`position` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `dept`
    FOREIGN KEY (`dept_id`)
    REFERENCES `hsrrs`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hsrrs`.`ticket_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hsrrs`.`ticket_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hsrrs`.`initial_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hsrrs`.`initial_ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ini_subject` VARCHAR(255) NOT NULL,
  `ini_status` VARCHAR(10) NOT NULL,
  `ini_priority` VARCHAR(10) NOT NULL,
  `ini_date` DATETIME NOT NULL,
  `ini_limit` TIME NOT NULL,
  `ROOM_id` INT NOT NULL,
  `receptionist` INT NOT NULL,
  `ticket_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_INITIAL TICKET_ROOM1_idx` (`ROOM_id` ASC),
  INDEX `fk_initial_ticket_employee1_idx` (`receptionist` ASC),
  INDEX `fk_initial_ticket_ticket_type1_idx` (`ticket_type_id` ASC),
  CONSTRAINT `fk_INITIAL TICKET_ROOM1`
    FOREIGN KEY (`ROOM_id`)
    REFERENCES `hsrrs`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_initial_ticket_employee1`
    FOREIGN KEY (`receptionist`)
    REFERENCES `hsrrs`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_initial_ticket_ticket_type1`
    FOREIGN KEY (`ticket_type_id`)
    REFERENCES `hsrrs`.`ticket_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hsrrs`.`finalized_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hsrrs`.`finalized_ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fin_closedtime` TIME NOT NULL,
  `initial_ticket_id` INT NOT NULL,
  `dept_staff` INT NOT NULL,
  `supervisor` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_finalized_ticket_initial_ticket1_idx` (`initial_ticket_id` ASC),
  INDEX `fk_finalized_ticket_employee1_idx` (`dept_staff` ASC),
  INDEX `fk_finalized_ticket_employee2_idx` (`supervisor` ASC),
  CONSTRAINT `fk_finalized_ticket_initial_ticket1`
    FOREIGN KEY (`initial_ticket_id`)
    REFERENCES `hsrrs`.`initial_ticket` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_finalized_ticket_employee1`
    FOREIGN KEY (`dept_staff`)
    REFERENCES `hsrrs`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_finalized_ticket_employee2`
    FOREIGN KEY (`supervisor`)
    REFERENCES `hsrrs`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
